[project]
name = "monarchmoney-mcp"
version = "0.1.0"
description = "by richardadonnell"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.6.0",
    "monarchmoney>=0.1.15",
]
